server:
  port: 9001

spring:
  application:
    name: auth-service
  main:
    web-application-type: reactive  # ✅ Important for WebFlux + Gateway
  datasource:
    url: jdbc:mysql://localhost:3306/aitask_user
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC   # ✅ avoids datetime default issues

  config:
    import: optional:configserver:http://localhost:8888  # ✅ enables Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
