server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chetan-Purkar/aitask-config.git
          clone-on-start: true
          default-label: main  # Use 'main' if your GitHub repo default branch is 'main'
